services:
  database:
    image: postgres
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=admin"
      - "POSTGRES_DB=cosmify"

volumes:
  database: