export enum ActionType {
  "FETCH_UPTIME" = "FETCH_UPTIME",
  "FETCH_SERVER_INFORMATION" = "FETCH_SERVER_INFORMATION",
  "UPGRADE_SERVER_PACKAGES" = "UPGRADE_SERVER_PACKAGES",
  "CHECK_COMMAND_AVAILABILITY" = "CHECK_COMMAND_AVAILABILITY",
  "INSTALL_DOCKER" = "INSTALL_DOCKER",
  "QUERY_CONTAINER_LOGS" = "QUERY_CONTAINER_LOGS",
  "QUERY_CONTAINER_STATS" = "QUERY_CONTAINER_STATS",
  "RUN_CONTAINER" = "RUN_CONTAINER",
  "RUN_COMPOSE_FILE" = "RUN_COMPOSE_FILE",
  "RESTART_COMPOSE_FILE" = "RESTART_COMPOSE_FILE",
  "STOP_COMPOSE_FILE" = "STOP_COMPOSE_FILE",
  "PULL_IMAGE" = "PULL_IMAGE",
  "CREATE_NETWORK" = "CREATE_NETWORK",
  "REMOVE_NETWORK" = "REMOVE_NETWORK",
  "REMOVE_CONTAINER" = "REMOVE_CONTAINER",
  "SAVE_FILE" = "SAVE_FILE",
  "CREATE_FILE" = "CREATE_FILE",
  "CREATE_DIRECTORY" = "CREATE_DIRECTORY",
  "REMOVE_PATH" = "REMOVE_PATH",
  "REMOVE_DOCKER" = "REMOVE_DOCKER"
}

export enum Status {
  "PENDING" = "PENDING",
  "INITIALIZING" = "INITIALIZING",
  "EXECUTING" = "EXECUTING",
  "PREPARING" = "PREPARING",
  "INSTALLING" = "INSTALLING",
  "SUCCESS" = "SUCCESS",
  "ERROR" = "ERROR",
  "ONLINE" = "ONLINE",
  "OFFLINE" = "OFFLINE",
  "DELETING" = "DELETING"
}

export enum TransactionStatus {
  "PENDING" = "PENDING",
  "EXECUTING" = "EXECUTING",
  "SUCCESS" = "SUCCESS",
  "ERROR" = "ERROR"
}
